package com.bingbaihanji.fxdecomplie.core.jadx.core.utils.android;

import com.bingbaihanji.fxdecomplie.core.jadx.api.ICodeWriter;
import com.bingbaihanji.fxdecomplie.core.jadx.api.plugins.input.data.AccessFlags;
import com.bingbaihanji.fxdecomplie.core.jadx.api.plugins.input.data.annotations.EncodedType;
import com.bingbaihanji.fxdecomplie.core.jadx.api.plugins.input.data.annotations.EncodedValue;
import com.bingbaihanji.fxdecomplie.core.jadx.core.codegen.ClassGen;
import com.bingbaihanji.fxdecomplie.core.jadx.core.deobf.NameMapper;
import com.bingbaihanji.fxdecomplie.core.jadx.core.dex.attributes.AFlag;
import com.bingbaihanji.fxdecomplie.core.jadx.core.dex.info.AccessInfo;
import com.bingbaihanji.fxdecomplie.core.jadx.core.dex.info.ClassInfo;
import com.bingbaihanji.fxdecomplie.core.jadx.core.dex.info.ConstStorage;
import com.bingbaihanji.fxdecomplie.core.jadx.core.dex.info.FieldInfo;
import com.bingbaihanji.fxdecomplie.core.jadx.core.dex.instructions.args.ArgType;
import com.bingbaihanji.fxdecomplie.core.jadx.core.dex.nodes.ClassNode;
import com.bingbaihanji.fxdecomplie.core.jadx.core.dex.nodes.FieldNode;
import com.bingbaihanji.fxdecomplie.core.jadx.core.dex.nodes.RootNode;
import com.bingbaihanji.fxdecomplie.core.jadx.core.xmlgen.ResourceStorage;
import com.bingbaihanji.fxdecomplie.core.jadx.core.xmlgen.entry.ResourceEntry;
import org.jetbrains.annotations.NotNull;
import org.slf4j.Logger;
import org.slf4j.LoggerFactory;

import java.util.HashMap;
import java.util.List;
import java.util.Map;
import java.util.TreeMap;

/**
 * Android 资源相关的专用处理工具类。
 * <p>
 * 负责搜索应用的 R 类、将资源 ID 注入 R 类内部类字段，
 * 以及在代码生成阶段处理资源字段的引用输出。
 */
public class AndroidResourcesUtils {
    private static final Logger LOG = LoggerFactory.getLogger(AndroidResourcesUtils.class);

    private AndroidResourcesUtils() {
    }

    /**
     * 查找（或在缺失时生成）应用的 R 资源类，并向其中注入资源字段。
     * <p>
     * 优先在应用包名下查找 {@code R} 类；找不到时按短名 {@code R} 搜索候选类；
     * 仍未找到则创建一个合成的 R 类用于承载所有资源 ID。
     *
     * @param root       根节点
     * @param resStorage 资源存储
     * @return 应用的 R 资源类节点
     */
    public static ClassNode searchAppResClass(RootNode root, ResourceStorage resStorage) {
        String appPackage = root.getAppPackage();
        String fullName = appPackage != null ? appPackage + ".R" : "R";
        ClassInfo clsInfo = ClassInfo.fromName(root, fullName);
        ClassNode resCls = root.resolveClass(clsInfo);
        if (resCls != null) {
            addResourceFields(resCls, resStorage, true);
            return resCls;
        }
        LOG.debug("Can't find 'R' class in app package: {}", appPackage);
        List<ClassNode> candidates = root.searchClassByShortName("R");
        if (candidates.size() == 1) {
            ClassNode resClsCandidate = candidates.get(0);
            addResourceFields(resClsCandidate, resStorage, true);
            return resClsCandidate;
        }
        if (!candidates.isEmpty()) {
            LOG.info("Found several 'R' class candidates: {}", candidates);
        }
        LOG.info("App 'R' class not found, put all resources ids into : '{}'", fullName);
        ClassNode rCls = ClassNode.addSyntheticClass(root, clsInfo, AccessFlags.PUBLIC | AccessFlags.FINAL);
        rCls.addInfoComment("This class is generated by JADX");
        addResourceFields(rCls, resStorage, false);
        return rCls;
    }

    /**
     * 处理 R 资源字段的引用，在代码中生成形如 {@code R.type.name} 的字段访问。
     *
     * @param code      代码写入器
     * @param clsGen    类代码生成器
     * @param declClass 字段所属的声明类
     * @return 若为 R 资源字段并已生成引用返回 true，否则返回 false
     */
    public static boolean handleAppResField(ICodeWriter code, ClassGen clsGen, ClassInfo declClass) {
        ClassInfo parentClass = declClass.getParentClass();
        if (parentClass != null && "R".equals(parentClass.getShortName())) {
            clsGen.useClass(code, parentClass);
            code.add('.');
            code.add(declClass.getAliasShortName());
            return true;
        }
        return false;
    }

    /**
     * 判断字段值是否为 Android 资源 ID，从而强制以十六进制格式输出。
     *
     * @param cls  字段所属类
     * @param type 字段类型
     * @return 为资源类中的 int 字段返回 true
     */
    public static boolean isResourceFieldValue(ClassNode cls, ArgType type) {
        return type.equals(ArgType.INT) && isResourceClass(cls);
    }

    /**
     * 判断指定类是否为 R 资源类的内部类型类（其父类别名为 {@code R}）。
     *
     * @param cls 待判断的类
     * @return 是资源类返回 true
     */
    public static boolean isResourceClass(ClassNode cls) {
        ClassNode parentClass = cls.getParentClass();
        return parentClass != null && "R".equals(parentClass.getAlias());
    }

    /**
     * 向 R 类中按资源类型补全资源字段。
     * <p>
     * 遍历资源存储中的每个资源，为其在对应类型的内部类中创建缺失的静态 final int 字段；
     * 若已存在同 ID 的常量字段但名称不同，则为其设置别名以恢复可读的资源名。
     *
     * @param resCls     R 资源类节点
     * @param resStorage 资源存储
     * @param rClsExists 目标 R 类是否为已存在的类（而非新生成的合成类）
     */
    private static void addResourceFields(ClassNode resCls, ResourceStorage resStorage, boolean rClsExists) {
        Map<Integer, FieldNode> resFieldsMap = fillResFieldsMap(resCls);
        Map<String, ResClsInfo> innerClsMap = new TreeMap<>();
        if (rClsExists) {
            for (ClassNode innerClass : resCls.getInnerClasses()) {
                ResClsInfo innerResCls = new ResClsInfo(innerClass);
                innerClass.getFields().forEach(field -> innerResCls.getFieldsMap().put(field.getName(), field));
                innerClsMap.put(innerClass.getAlias(), innerResCls);
            }
        }
        for (ResourceEntry resource : resStorage.getResources()) {
            String resTypeName = resource.getTypeName();
            String resName = resource.getKeyName().replace('.', '_');

            ResClsInfo typeClsInfo = innerClsMap.computeIfAbsent(
                    resTypeName,
                    name -> getClassForResType(resCls, rClsExists, name));
            typeClsInfo.getFieldsMap().computeIfAbsent(resName, name -> {
                ClassNode typeCls = typeClsInfo.getTypeCls();
                FieldInfo rFieldInfo = FieldInfo.from(typeCls.root(), typeCls.getClassInfo(), resName, ArgType.INT);
                FieldNode newResField = new FieldNode(typeCls, rFieldInfo,
                        AccessFlags.PUBLIC | AccessFlags.STATIC | AccessFlags.FINAL);
                newResField.addAttr(new EncodedValue(EncodedType.ENCODED_INT, resource.getId()));
                typeCls.addField(newResField);
                if (rClsExists) {
                    newResField.addInfoComment("Added by JADX");
                }
                return newResField;
            });
            FieldNode fieldNode = resFieldsMap.get(resource.getId());
            if (fieldNode != null
                    && !fieldNode.getName().equals(resName)
                    && NameMapper.isValidAndPrintable(resName)
                    && resCls.root().getArgs().isRenameValid()) {
                fieldNode.add(AFlag.DONT_RENAME);
                fieldNode.getFieldInfo().setAlias(resName);
            }
        }
    }

    /**
     * 获取（或在缺失时创建）指定资源类型对应的内部类型类。
     *
     * @param resCls     R 资源类节点
     * @param rClsExists R 类是否为已存在的类
     * @param typeName   资源类型名（如 string、layout）
     * @return 对应资源类型类的信息
     */
    private static ResClsInfo getClassForResType(ClassNode resCls, boolean rClsExists, String typeName) {
        RootNode root = resCls.root();
        String typeClsFullName = resCls.getClassInfo().makeRawFullName() + '$' + typeName;
        ClassInfo clsInfo = ClassInfo.fromName(root, typeClsFullName);
        ClassNode existCls = root.resolveClass(clsInfo);
        if (existCls != null) {
            ResClsInfo resClsInfo = new ResClsInfo(existCls);
            existCls.getFields().forEach(field -> resClsInfo.getFieldsMap().put(field.getName(), field));
            return resClsInfo;
        }
        ClassNode newTypeCls = ClassNode.addSyntheticClass(root, clsInfo,
                AccessFlags.PUBLIC | AccessFlags.STATIC | AccessFlags.FINAL);
        if (rClsExists) {
            newTypeCls.addInfoComment("Added by JADX");
        }
        return new ResClsInfo(newTypeCls);
    }

    /**
     * 收集全局常量中所有静态 final 的 int 字段，构建资源 ID 到字段节点的映射。
     *
     * @param resCls R 资源类节点
     * @return 资源 ID 到字段节点的映射
     */
    @NotNull
    private static Map<Integer, FieldNode> fillResFieldsMap(ClassNode resCls) {
        Map<Integer, FieldNode> resFieldsMap = new HashMap<>();
        ConstStorage constStorage = resCls.root().getConstValues();
        constStorage.getGlobalConstFields().forEach((key, field) -> {
            if (field.getFieldInfo().getType().equals(ArgType.INT)
                    && field instanceof FieldNode
                    && key instanceof Integer) {
                FieldNode fldNode = (FieldNode) field;
                AccessInfo accessFlags = fldNode.getAccessFlags();
                if (accessFlags.isStatic() && accessFlags.isFinal()) {
                    resFieldsMap.put((Integer) key, fldNode);
                }
            }
        });
        return resFieldsMap;
    }

    /**
     * 资源类型类信息，持有某一资源类型（如 string、drawable）对应的内部类节点
     * 及其字段名到字段节点的映射。
     */
    private static final class ResClsInfo {
        private final ClassNode typeCls;
        private final Map<String, FieldNode> fieldsMap = new HashMap<>();

        private ResClsInfo(ClassNode typeCls) {
            this.typeCls = typeCls;
        }

        public ClassNode getTypeCls() {
            return typeCls;
        }

        public Map<String, FieldNode> getFieldsMap() {
            return fieldsMap;
        }
    }
}
